In [18]:
import json
import os
import sys

import requests
import pandas as pd
import time
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv
import sys
sys.path.insert(0, "../") #Se mettre à la racine directe pour importer les fonctions du dossier src
from src.config.config import OUTPUT_PATH_PROCESSED
from src.data_cleaning.download_data import scrape_subreddit, all_posts_listed, save_posts_to_csv

In [ ]:
#######################################  Download data from all the Subreddits from the SUBREDDITS variable in config.py
#Uncomment the line below to download data.
#df = all_posts_listed()

In [3]:
#Uncomment the line below to save the data to a CSV file.
#save_posts_to_csv(df, OUTPUT_PATH)

In [4]:
df = pd.read_csv("../data/raw/happiness_reddit.csv")

In [5]:
#We add a label 0 for non depressed since we scrapped from happy subreddits
df["label"] = 0

In [6]:
sys.path.insert(0, "../")
from src.data_cleaning.clean_data import clean_data_scrapped
df_cleaned = clean_data_scrapped(df)
df_cleaned.head()

                                               title  label
0  My grandmother found a seller of my favorite d...      0
1  Absolute WIN! I flew economy and was put in th...      0
2        [OC] For a moment, I felt like a kid again       0
3  Appreciating my kids while they're little enou...      0
4  I finally found a best friend and I’ve never b...      0

In [7]:
df_cleaned.shape

(13637, 2)

In [ ]:
###################################################################### DOWNLOAD DATA FROM KAGGLE ###############################################################################################

In [9]:
sys.path.insert(0, "../")
from src.data_cleaning.download_data import download_data_kaggle
download_data_kaggle()

Dataset déjà téléchargé, téléchargement ignoré.

In [10]:
df_kaggle = pd.read_csv("../data/raw/reddit_depression_dataset.csv")
df_kaggle.head()

/tmp/ipykernel_203374/2049458755.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_kaggle = pd.read_csv("../data/raw/reddit_depression_dataset.csv")

,Unnamed: 0,subreddit,title,body,upvotes,created_utc,num_comments,label
0,47951,DeepThoughts,Deep thoughts underdog,"Only when we start considering ourselves, the ...",4.0,1.405309e+09,NaN,0.0
1,47952,DeepThoughts,"I like this sub, there's only two posts yet I ...",Anyway: Human Morality is a joke so long as th...,4.0,1.410568e+09,1.0,0.0
2,47957,DeepThoughts,Rebirth!,Hello. \nI am the new guy in charge here (Besi...,6.0,1.416458e+09,1.0,0.0
3,47959,DeepThoughts,"""I want to be like water. I want to slip throu...",NaN,25.0,1.416512e+09,2.0,0.0
4,47960,DeepThoughts,Who am I?,You could take any one cell in my body and kil...,5.0,1.416516e+09,4.0,0.0

In [11]:
df_kaggle.value_counts("label")

label
0.0    1990261
1.0     480411
Name: count, dtype: int64

In [12]:
sys.path.insert(0, "../")
from src.data_cleaning.clean_data import clean_data_kaggle
df_kaggle = clean_data_kaggle(df_kaggle)

In [13]:
df_kaggle.value_counts("label"), df_cleaned.value_counts("label")

(label
 0.0    1990260
 1.0     480409
 Name: count, dtype: int64,
 label
 0    13637
 Name: count, dtype: int64)

In [14]:
sys.path.insert(0, "../")
from src.data_cleaning.balance_classes import balance_classes, remove_label0_kaggle
df_dep = remove_label0_kaggle(df_kaggle)
df_balanced = balance_classes(df_dep, df_cleaned)

Balancing to 13,637 rows per class.

Final dataset shape: (27274, 2)
label
1.0    13637
0.0    13637
Name: count, dtype: int64

In [ ]:
#Uncomment to save the balanced dataset to a CSV file.
#save_posts_to_csv(df_balanced, OUTPUT_PATH_PROCESSED)