In [1]:
import json
import os
import sys

import requests
import pandas as pd
import time
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv
import sys
sys.path.insert(0, "../") #Se mettre à la racine directe pour importer les fonctions du dossier src
from src.data_cleaning.download_data import scrape_subreddit, all_posts_listed, save_posts_to_csv
from src.config.config import SUBREDDITS, MAX_POSTS_PER_SUBREDDIT, SLEEP_BETWEEN_REQUESTS, OUTPUT_PATH, HEADERS

In [ ]:
#Download data from all the Subreddits from the SUBREDDITS variable in config.py
df = all_posts_listed()

Scraping r/happy ... 99 199 295 394 487 578 672 764 856 952 -> 952 posts collected
Scraping r/Happiness ... 97 195 294 394 490 581 680 777 872 962 -> 962 posts collected
Scraping r/joy ... 96 127 -> 127 posts collected
Scraping r/aww ... 99 199 298 397 497 597 697 797 897 995 -> 995 posts collected
Scraping r/wholesomememes ... 100 198 293 391 489 583 676 775 868 958 -> 958 posts collected
Scraping r/UpliftingNews ... 98 196 293 389 487 580 666 755 844 913 -> 913 posts collected
Scraping r/GetMotivated ... 99 199 299 398 496 595 695 789 885 957 -> 957 posts collected
Scraping r/CasualConversation ... 98 197 296 396 493 591 688 786 881 976 977 -> 977 posts collected
Scraping r/Mindfulness ... 97 196 294 391 490 584 682 780 876 975 -> 975 posts collected
Scraping r/gratitude ... 98 198 297 396 494 593 692 787 878 975 -> 975 posts collected
Scraping r/selfimprovement ... 100 199 299 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 rate limited, waiting 30s ...
 399 499 598 697 795 895 995 -> 995 posts collected
Scraping r/mildlyinteresting ... 99 199 299 399 499 599 699 799 899 999 -> 999 posts collected
Scraping r/Wellbeing ... 98 187 283 377 467 553 651 751 847 905 -> 905 posts collected
Scraping r/funny ... 99 199 299 399 499 598 698 798 896 993 -> 993 posts collected
Scraping r/todayilearned ... 100 196 293 390 488 583 669 762 856 954 -> 954 posts collected

In [ ]:
#save_posts_to_csv(df, OUTPUT_PATH)

In [2]:
df = pd.read_csv("../data/raw/happiness_reddit.csv")

In [3]:
#We add a label for non depressed since we scrapped from happy subreddits
df["label"] = 0

In [4]:
df.head()

,subreddit,title,body,score,num_comments,created_utc,label
0,happy,My grandmother found a seller of my favorite d...,"so a few years back, my grandma was going thro...",310,8,2026-04-06 04:44:43,0
1,happy,Absolute WIN! I flew economy and was put in th...,I was dreading my flight schedule as I knew I'...,102,2,2026-04-06 05:38:31,0
2,happy,"[OC] For a moment, I felt like a kid again",NaN,264,9,2026-04-05 22:11:43,0
3,happy,Appreciating my kids while they're little enou...,I've been working on making a game in my spare...,50,7,2026-04-06 03:31:35,0
4,happy,I finally found a best friend and I’ve never b...,He came out of the blew working at my job and ...,12,3,2026-04-06 08:23:55,0

In [5]:
sys.path.insert(0, "../")
from src.data_cleaning.clean_data import clean_data_scrapped
df_cleaned = clean_data_scrapped(df)
df_cleaned.head()

                                               title  label
0  My grandmother found a seller of my favorite d...      0
1  Absolute WIN! I flew economy and was put in th...      0
2        [OC] For a moment, I felt like a kid again       0
3  Appreciating my kids while they're little enou...      0
4  I finally found a best friend and I’ve never b...      0

In [6]:
df_cleaned.shape

(13637, 2)